### PR TITLE
[doc] Editorial suggestions for "Symbols and Punctuation Characters"

### PR DESCRIPTION
**Pull request by kojiishi**
Suggestions from @kidayasuo.

### CODE REVIEW

**Comment by kidayasuo** [comment]
thank you. The change look good except that I want to change the first sentence to "…practices do not consider such unbalanced spacing as an issue." or "…practices consider such unbalanced spacing as non-issue.".

**Comment by kojiishi** [comment]
> thank you. The change look good except that I want to change the first sentence to "…practices do not consider such unbalanced spacing as an issue." or "…practices consider such unbalanced spacing as non-issue.".

@kidayasuo Can I ask your intention?

Both suggestions read to me that "not an issue", which sounds like "ok-ish" or "acceptable" to me, and is weaker than "good" or "prefer". Is your intention to weaken the practice to "ok", leaving how much it's preferred undefined?

**Comment by kojiishi** [comment]
If your intention is not about weakening the sentence but somehow the grammer doesn't look good, how about:
```
-On the other hand, some other existing practices consider
-such unbalanced spacing as good results.
+On the other hand, some other existing practices prefer
+such unbalanced spacing.
```
?

**Comment by kojiishi** [comment]
Pushed the "prefer" change.

**Comment by kidayasuo** [comment]
The other practice does not prefer unbalanced spacing. Rather, it does not evaluate spacing in terms of being balanced or unbalanced at all. It does not view spacing as parentheses that need to be balanced. Instead, its focus is solely on legibility. Therefore, whether the spacing appears balanced or not is not even a consideration in this practice.

**Review by kidayasuo — CHANGES_REQUESTED** [review]
The other practice does not prefer unbalanced spacing. Rather, it does not evaluate spacing in terms of being balanced or unbalanced at all. It does not view spacing as parentheses that need to be balanced. Instead, its focus is solely on legibility. Therefore, whether the spacing appears balanced or not is not even a consideration in this practice.

**Comment by kidayasuo** [comment]
I suggest to change the first sentence like below

"On the other hand, some other existing practices do not evaluate spacing in terms of being balanced or unbalanced."

Otherwise the change looks good.

**Comment by kojiishi** [comment]
Discussed offline and reached a consensus.

**Review by kidayasuo — COMMENTED** [review]
The change solves the issue I raised. Approving. Thank you.
Actually, how do I approve after having requested a change?

**Pull request merged**
